# -*- coding: utf-8 -*-
"""
/***************************************************************************
 sdna_plugin
                                 A QGIS plugin
 This plugin allows you to use your installation of sDNA from within the QGIS GIS software.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-07-08
        copyright            : (C) 2020 by Jeffrey Morgan
        email                : MorganJ51@cardiff.ac.uk
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Jeffrey Morgan'
__date__ = '2020-07-08'
__copyright__ = '(C) 2020 by Jeffrey Morgan'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load sdna_plugin class from file sdna_plugin.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .sdna_plugin import SDNAPlugin
    return SDNAPlugin()
